baseurl = "https://cubl.in/"
languageCode = "zh-cn"
title = "/home/cubl"
theme = "hugo-lithium"
googleAnalytics = "UA-54867602-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = false

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "Index"
    url = "/"
    weight = -1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cubarco/cubarco.github.io"
    weight = 3

[params]
    ghmirror = "https://cdn.jsdelivr.net/gh/cubarco/cubarco.github.io@gh-pages"
    description = "Pwning for fun."
    umamiWebsiteId = "e9fdcc32-0bfa-4de5-beb0-3bbf1e4638ab"
    umamiSrcUrl = "https://umami.pwn.ooo/umami.js"

    # options for highlight.js (version, additional languages, and theme)
    #highlightjsVersion = "9.12.0"
    #highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #highlightjsLang = ["r", "yaml"]
    #highlightjsTheme = "github"

    disable_mathjax = true
    #MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo-min.png"
    width = 50
    height = 50
    alt = "Logo"

#[markup]
#  defaultMarkdownHandler = "goldmark"
#  [markup.goldmark.renderer]
#    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
#  #[markup.highlight]
    #lineNos = true
    #style = "github"
