name = "cubl-blog"
account_id = "a2059eb38b7c3197606f8534aedbcf56"
compatibility_date = "2023-12-21"
main = ".workers-site/index.js"
#workers_dev = true

[site]
bucket = "./public"

[env.production]
route = "cubar.co/*"
