name = "cubl-blog"
type = "webpack"
account_id = "a2059eb38b7c3197606f8534aedbcf56"
#workers_dev = true

[site]
bucket = "./public"
entry-point = ".workers-site"

[env.production]
zone_id = "268adf7e532bae85f741a8e4c69331d9"
route = "cubarco.org/*"
